rsa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import re_path as url
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("users.urls", namespace="users")),
    # Your stuff: custom urls includes go here
    path('core/', include('core.urls', namespace='core')),
    path("sociedad/", include("sociedad.urls", namespace="sociedades")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('', include('login.urls', namespace='login')), ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sociedad/urls.py
from django.urls import path

from .resources import ContinenteMasExportadoApi, LenguajeMasExportadoApi, EstadosMasRegistradoApi, ContinenteNoExportadoApi, RechazadosApi, \
    CantidadEsperaApi, CantidadAutoaceptadosApi, CantidadDiasProcesoApi, CantidadDiasMesaEntradaApi, CantidadDiasAreaLegalesApi
from .views import Registrar, Listar, SociedadVer, SociedadVer, Editar, Cerrar, Revisar, Rechazar, Confirmar, RechazarConfirmacion, SociedadVerPublico, \
    CarpetasGeneradas

app_name = 'liquidacion'

urlpatterns = [
    path('registrar', Registrar.as_view(), name='registrar'),
    path('listar-sociedades', Listar.as_view(), name='listar'),
    path('sociedad/<int:pk>', SociedadVer.as_view(), name='sociedad'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('cerrar/<int:pk>', Cerrar.as_view(), name='cerrar'),
    path('revisar/<int:pk>', Revisar.as_view(), name='revisar'),
    path('rechazar/<int:pk>', Rechazar.as_view(), name='rechazar'),
    path('confirmar/<int:pk>', Confirmar.as_view(), name='confirmar'),
    path('rechazar-confirmacion/<int:pk>', RechazarConfirmacion.as_view(), name='rechazar_confirmacion'),
    path('publica/<str:hash>', SociedadVerPublico.as_view(), name='sociedad_publica'),
    path('carpetas-generadas/<int:pk>', CarpetasGeneradas.as_view(), name='carpetas_generadas'),

    #API
    path('continentes-mas-exportados', ContinenteMasExportadoApi.as_view(), name='continentes_mas_exportados'),
    path('lenguaje-mas-exportados', LenguajeMasExportadoApi.as_view(), name='lenguaje_mas_exportados'),
    path('estados-mas-registrados', EstadosMasRegistradoApi.as_view(), name='estados_mas_registrados'),
    path('continentes-no-exportados', ContinenteNoExportadoApi.as_view(), name='continentes_no_exportados'),

    #API DATOS
    path('rechazados', RechazadosApi.as_view(), name='rechazados'),
    path('cantidad-espera', CantidadEsperaApi.as_view(), name='cantidad_espera'),
    path('cantidad-autoaceptados', CantidadAutoaceptadosApi.as_view(), name='cantidad_autoaceptados'),
    path('cantidad-dias-proceso', CantidadDiasProcesoApi.as_view(), name='cantidad_dias_proceso'),
    path('cantidad-dias-mesa-entrada', CantidadDiasMesaEntradaApi.as_view(), name='cantidad_dias_mesa_entrada'),
    path('cantidad-dias-area-legales', CantidadDiasAreaLegalesApi.as_view(), name='cantidad_dias_area_legales'),
]

templates/pages/about.html
{% extends "base.html" %}

templates/pages/home.html
{% extends "base.html" %}

{% block content %}
{% if user.personal_direccion %}
    <div class="container">

        <div class="card-columns">
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Rechazados
                        </h5>
                        <canvas id="myChart" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Esperas
                        </h5>
                        <canvas id="myChart1" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Autoaceptados
                        </h5>
                        <canvas id="myChart2" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Cantidad Días Proceso Completo
                        </h5>
                        <canvas id="myChart3" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Cantidad Días Mesa de Entrada
                        </h5>
                        <canvas id="myChart4" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
            <div class="card border-info">
                <div class="card-body">
                    <div class="card-body">
                        <h5 class="card-title">
                            Cantidad Días Area de Legales
                        </h5>
                        <canvas id="myChart5" width="400" height="400"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block extra_js %}
{% if user.personal_direccion %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"></script>
    <script>
        let endpoint = '{% url 'sociedades:rechazados' %}';
        let items = [];
        let labels = [];
        $.ajax({
            method: 'GET',
            url: endpoint,
            success: function (data) {
                console.log(data);
                labels = data.labels;
                items = data.items;
                setChart()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart() {
            let ctx = document.getElementById('myChart');
            let myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels,
                    datasets: [{
                        label: '# Rechazados',
                        data: items,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }


        let endpoint1 = '{% url 'sociedades:cantidad_espera' %}';
        let items1 = [];
        let labels1 = [];
        $.ajax({
            method: 'GET',
            url: endpoint1,
            success: function (data) {
                console.log(data);
                labels1 = data.labels;
                items1 = data.items;
                setChart1()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart1() {
            let ctx = document.getElementById('myChart1');
            let myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels1,
                    datasets: [{
                        label: '# Esperas',
                        data: items1,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }


        let endpoint2 = '{% url 'sociedades:cantidad_autoaceptados' %}';
        let items2 = [];
        let labels2 = [];
        $.ajax({
            method: 'GET',
            url: endpoint2,
            success: function (data) {
                console.log(data);
                labels2 = data.labels;
                items2 = data.items;
                setChart2()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart2() {
            let ctx = document.getElementById('myChart2');
            let myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: labels2,
                    datasets: [{
                        label: '# Autoaceptados',
                        data: items2,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }

        let endpoint3 = '{% url 'sociedades:cantidad_dias_proceso' %}';
        let items3 = [];
        let labels3 = [];
        $.ajax({
            method: 'GET',
            url: endpoint3,
            success: function (data) {
                console.log(data);
                labels3 = data.labels;
                items3 = data.items;
                setChart3()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart3() {
            let ctx = document.getElementById('myChart3');
            let myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels3,
                    datasets: [{
                        label: '# Dias Proceso',
                        data: items3,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d",
                            "#ad8bc9"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728",
                            "#9467bd"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }


        let endpoint4 = '{% url 'sociedades:cantidad_dias_mesa_entrada' %}';
        let items4 = [];
        let labels4 = [];
        $.ajax({
            method: 'GET',
            url: endpoint4,
            success: function (data) {
                console.log(data);
                labels4 = data.labels;
                items4 = data.items;
                setChart4()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart4() {
            let ctx = document.getElementById('myChart4');
            let myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels4,
                    datasets: [{
                        label: '# Dias Mesa Entrada',
                        data: items4,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d",
                            "#ad8bc9"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728",
                            "#9467bd"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }


        let endpoint5 = '{% url 'sociedades:cantidad_dias_area_legales' %}';
        let items5 = [];
        let labels5 = [];
        $.ajax({
            method: 'GET',
            url: endpoint5,
            success: function (data) {
                console.log(data);
                labels5 = data.labels;
                items5 = data.items;
                setChart5()
            },
            error: function (error_data) {
                console.log('error');
                console.log(error_data)
            }
        });

        function setChart5() {
            let ctx = document.getElementById('myChart5');
            let myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels5,
                    datasets: [{
                        label: '# Dias Area Legales',
                        data: items5,
                        backgroundColor: [
                            "#729ece",
                            "#ff9e4a",
                            "#67bf5c",
                            "#ed665d",
                            "#ad8bc9"],

                        borderColor: [
                            "#1f77b4",
                            "#ff7f0e",
                            "#2ca02c",
                            "#d62728",
                            "#9467bd"],
                        borderWidth: 1
                    }],
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true,
                                stepSize: 1,
                                fixedStepSize: 1,
                            },
                        }]
                    }
                }
            })
        }
    </script>
{% endif %}
{% endblock %}