rsa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import re_path as url
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("users.urls", namespace="users")),
    # Your stuff: custom urls includes go here
    path('core/', include('core.urls', namespace='core')),
    path("sociedad/", include("sociedad.urls", namespace="sociedades")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('', include('login.urls', namespace='login')), ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sociedad/urls.py
from django.urls import path

from .resources import ContinenteMasExportadoApi, LenguajeMasExportadoApi, EstadosMasRegistradoApi, ContinenteNoExportadoApi, RechazadosApi, \
    CantidadEsperaApi, CantidadAutoaceptadosApi, CantidadDiasProcesoApi, CantidadDiasMesaEntradaApi, CantidadDiasAreaLegalesApi
from .views import Registrar, Listar, SociedadVer, SociedadVer, Editar, Cerrar, Revisar, Rechazar, Confirmar, RechazarConfirmacion, SociedadVerPublico, \
    CarpetasGeneradas

app_name = 'liquidacion'

urlpatterns = [
    path('registrar', Registrar.as_view(), name='registrar'),
    path('listar-sociedades', Listar.as_view(), name='listar'),
    path('sociedad/<int:pk>', SociedadVer.as_view(), name='sociedad'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('cerrar/<int:pk>', Cerrar.as_view(), name='cerrar'),
    path('revisar/<int:pk>', Revisar.as_view(), name='revisar'),
    path('rechazar/<int:pk>', Rechazar.as_view(), name='rechazar'),
    path('confirmar/<int:pk>', Confirmar.as_view(), name='confirmar'),
    path('rechazar-confirmacion/<int:pk>', RechazarConfirmacion.as_view(), name='rechazar_confirmacion'),
    path('publica/<str:hash>', SociedadVerPublico.as_view(), name='sociedad_publica'),
    path('carpetas-generadas/<int:pk>', CarpetasGeneradas.as_view(), name='carpetas_generadas'),

    #API
    path('continentes-mas-exportados', ContinenteMasExportadoApi.as_view(), name='continentes_mas_exportados'),
    path('lenguaje-mas-exportados', LenguajeMasExportadoApi.as_view(), name='lenguaje_mas_exportados'),
    path('estados-mas-registrados', EstadosMasRegistradoApi.as_view(), name='estados_mas_registrados'),
    path('continentes-no-exportados', ContinenteNoExportadoApi.as_view(), name='continentes_no_exportados'),

    #API DATOS
    path('rechazados', RechazadosApi.as_view(), name='rechazados'),
    path('cantidad-espera', CantidadEsperaApi.as_view(), name='cantidad_espera'),
    path('cantidad-autoaceptados', CantidadAutoaceptadosApi.as_view(), name='cantidad_autoaceptados'),
    path('cantidad-dias-proceso', CantidadDiasProcesoApi.as_view(), name='cantidad_dias_proceso'),
    path('cantidad-dias-mesa-entrada', CantidadDiasMesaEntradaApi.as_view(), name='cantidad_dias_mesa_entrada'),
    path('cantidad-dias-area-legales', CantidadDiasAreaLegalesApi.as_view(), name='cantidad_dias_area_legales'),
]

sociedad/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView, FormView, ListView

from django.forms.models import model_to_dict
from datetime import date, timedelta
import time

from core.views import ConfirmView
from users.mixins import EsEmpleadoMesaEntradaMixin, EsEmpleadoAreaLegalesMixin, EsApoderadoMixin
from users.models import User
from .helpers import crear_sociedad, editar_sociedad, revisar_sociedad, rechazar_sociedad, confirmar_sociedad, confirmar_sociedad_automatica, rechazar_confirmacion_sociedad, solicitar_estampillado, generar_qr, generar_carpetas, ConectorAPIBonita
from .forms import SociedadForm, SociedadEditarForm, RechazarForm, RechazarConfirmacionForm, PaisEstadoFormSet, DomicilioRealFormSet, DomicilioLegalFormSet, SocioFormSet
from .models import Sociedad


class Registrar(LoginRequiredMixin, EsApoderadoMixin, FormView):
    template_name = 'sociedad/registrar.html'
    form_class = SociedadForm

    def get_context_data(self, **kwargs):
        context = super(Registrar, self).get_context_data(**kwargs)
        context['title'] = 'Sociedad'
        context['url_cancelar'] = reverse_lazy('sociedades:listar')
        
        if 'formset' not in context:
            context['formset'] = PaisEstadoFormSet(prefix='exporta')
        if 'form_dom_real' not in context:
            context['form_dom_real'] = DomicilioRealFormSet(prefix='dom_real')
        if 'form_dom_legal' not in context:
            context['form_dom_legal'] = DomicilioLegalFormSet(prefix='dom_legal')
        if 'form_socio' not in context:
            context['form_socio'] = SocioFormSet(prefix='socios')

        return context

    def post(self, request, *args, **kwargs):
        form = SociedadForm(self.request.POST, self.request.FILES)

        formset = PaisEstadoFormSet(self.request.POST, prefix='exporta')

        form_dom_real = DomicilioRealFormSet(self.request.POST, prefix='dom_real')

        form_dom_legal = DomicilioLegalFormSet(self.request.POST, prefix='dom_legal')

        form_socio = SocioFormSet(self.request.POST, prefix='socios')

        if form.is_valid() and formset.is_valid() and form_dom_real.is_valid() and form_dom_legal.is_valid() and form_socio.is_valid():
            return self.form_valid(form, formset, form_dom_real, form_dom_legal, form_socio)
        else:
            return self.form_invalid(form, formset, form_dom_real, form_dom_legal, form_socio)

    def form_valid(self, form, formset, form_dom_real, form_dom_legal, form_socio):
        nombre = form.cleaned_data['nombre']
        fecha_creacion = form.cleaned_data['fecha_creacion']
        archivo_estatuto = form.cleaned_data['archivo_estatuto']
        email = form.cleaned_data['email']

        domicilio_real = {
            'pais_dom_real' : form_dom_real[0].cleaned_data['pais_dom_real'],
            'estado_dom_real' : form_dom_real[0].cleaned_data['estado_dom_real'],
            'localidad' : form_dom_real[0].cleaned_data['localidad'],
            'codigo_postal' : form_dom_real[0].cleaned_data['codigo_postal'],
            'calle' : form_dom_real[0].cleaned_data['calle'],
            'numero' : form_dom_real[0].cleaned_data['numero'],
            'piso' : form_dom_real[0].cleaned_data['piso'],
            'departamento' : form_dom_real[0].cleaned_data['departamento']
        }

        domicilio_legal = {
            'pais_dom_legal' : form_dom_legal[0].cleaned_data['pais_dom_legal'],
            'estado_dom_legal' : form_dom_legal[0].cleaned_data['estado_dom_legal'],
            'localidad' : form_dom_legal[0].cleaned_data['localidad'],
            'codigo_postal' : form_dom_legal[0].cleaned_data['codigo_postal'],
            'calle' : form_dom_legal[0].cleaned_data['calle'],
            'numero' : form_dom_legal[0].cleaned_data['numero'],
            'piso' : form_dom_legal[0].cleaned_data['piso'],
            'departamento' : form_dom_legal[0].cleaned_data['departamento']
        }

        socios = []
        for f in form_socio:
            socios.append({
                'nombres' : f.cleaned_data['nombres'],
                'apellidos' : f.cleaned_data['apellidos'],
                'aporte' : f.cleaned_data['aporte'],
                'apoderado' : f.cleaned_data['apoderado']
            })

        exportaciones = []
        for f in formset:
            try:
                if f.cleaned_data['pais'] != '':
                    exportaciones.append({
                        'pais_codigo' : f.cleaned_data['pais'],
                        'estado_descripcion' : f.cleaned_data['estado']
                    })
            except KeyError:
                pass

        agregado = crear_sociedad(self.request.user, nombre, fecha_creacion, archivo_estatuto, email, domicilio_real, domicilio_legal, socios, exportaciones)

        if agregado:
            conectorAPIBonita = ConectorAPIBonita()
            agregado.id_caso = conectorAPIBonita.instanciar_caso(self.request.user)
            agregado.save()
            messages.success(self.request, 'Se cargó correctamente la sociedad')
        else:
            messages.error(self.request, 'No se pudo cargar la sociedad')
        
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset, form_dom_real, form_dom_legal, form_socio):
        return self.render_to_response(self.get_context_data(form=form, formset=formset, form_dom_real=form_dom_real, form_dom_legal=form_dom_legal, form_socio=form_socio))

    def get_success_url(self):
        return reverse_lazy('sociedades:listar')


class Editar(LoginRequiredMixin, EsApoderadoMixin, FormView):
    template_name = 'sociedad/registrar.html'
    form_class = SociedadEditarForm

    def get_context_data(self, **kwargs):
        context = super(Editar, self).get_context_data(**kwargs)
        context['title'] = 'Sociedad'
        context['url_cancelar'] = reverse_lazy('sociedades:sociedad', kwargs={'pk': self.kwargs['pk']})

        sociedad = Sociedad.objects.get(pk=self.kwargs['pk'])
        context['form'] = SociedadEditarForm(initial=model_to_dict(sociedad))
        context['formset'] = PaisEstadoFormSet(prefix='exporta')
        context['form_dom_real'] = DomicilioRealFormSet(prefix='dom_real')
        context['form_dom_legal'] = DomicilioLegalFormSet(prefix='dom_legal')
        context['form_socio'] = SocioFormSet(prefix='socios')

        return context

    def post(self, request, *args, **kwargs):
        form = SociedadEditarForm(self.request.POST, self.request.FILES)

        formset = PaisEstadoFormSet(self.request.POST, prefix='exporta')

        form_dom_real = DomicilioRealFormSet(self.request.POST, prefix='dom_real')

        form_dom_legal = DomicilioLegalFormSet(self.request.POST, prefix='dom_legal')

        form_socio = SocioFormSet(self.request.POST, prefix='socios')

        if form.is_valid() and formset.is_valid() and form_dom_real.is_valid() and form_dom_legal.is_valid() and form_socio.is_valid():
            return self.form_valid(form, formset, form_dom_real, form_dom_legal, form_socio)
        else:
            return self.form_invalid(form, formset, form_dom_real, form_dom_legal, form_socio)

    def form_valid(self, form, formset, form_dom_real, form_dom_legal, form_socio):
        nombre = form.cleaned_data['nombre']
        fecha_creacion = form.cleaned_data['fecha_creacion']
        email = form.cleaned_data['email']

        sociedad = Sociedad.objects.get(pk=self.kwargs['pk'])

        domicilio_real = {
            'pais_dom_real' : form_dom_real[0].cleaned_data['pais_dom_real'],
            'estado_dom_real' : form_dom_real[0].cleaned_data['estado_dom_real'],
            'localidad' : form_dom_real[0].cleaned_data['localidad'],
            'codigo_postal' : form_dom_real[0].cleaned_data['codigo_postal'],
            'calle' : form_dom_real[0].cleaned_data['calle'],
            'numero' : form_dom_real[0].cleaned_data['numero'],
            'piso' : form_dom_real[0].cleaned_data['piso'],
            'departamento' : form_dom_real[0].cleaned_data['departamento']
        }

        domicilio_legal = {
            'pais_dom_legal' : form_dom_legal[0].cleaned_data['pais_dom_legal'],
            'estado_dom_legal' : form_dom_legal[0].cleaned_data['estado_dom_legal'],
            'localidad' : form_dom_legal[0].cleaned_data['localidad'],
            'codigo_postal' : form_dom_legal[0].cleaned_data['codigo_postal'],
            'calle' : form_dom_legal[0].cleaned_data['calle'],
            'numero' : form_dom_legal[0].cleaned_data['numero'],
            'piso' : form_dom_legal[0].cleaned_data['piso'],
            'departamento' : form_dom_legal[0].cleaned_data['departamento']
        }

        socios = []
        for f in form_socio:
            socios.append({
                'nombres' : f.cleaned_data['nombres'],
                'apellidos' : f.cleaned_data['apellidos'],
                'aporte' : f.cleaned_data['aporte'],
                'apoderado' : f.cleaned_data['apoderado']
            })

        exportaciones = []
        for f in formset:
            try:
                if f.cleaned_data['pais'] != '':
                    exportaciones.append({
                        'pais_codigo' : f.cleaned_data['pais'],
                        'estado_descripcion' : f.cleaned_data['estado']
                    })
            except KeyError:
                pass

        agregado = editar_sociedad(self.request.user, sociedad, nombre, fecha_creacion, email, domicilio_real, domicilio_legal, socios, exportaciones)

        if agregado:

sociedad/templates/sociedad/listar.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Listado Sociedades{% endblock title %}

{% block content %}

    <div class="card border-info">
        <div class="card-body">
            <h2 class="card-title">
                Sociedades
            </h2>

            {% if not user.empleado_mesa_entrada and not user.empleado_area_legales %}
            <div class="mb-3">
                <a class="btn btn-primary" href="{% url 'sociedades:registrar' %}">Nueva Sociedad</a>
            </div>
            {% endif %}

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nombre</th>
                    <th scope="col">Fecha Creación</th>
                    <th scope="col">Apoderado</th>
                    <th scope="col">Estado</th>
                </tr>
                </thead>
                <tbody>
                {% for sociedad in sociedades %}
                    <tr>
                        <td scope="row"><a href="{% url 'sociedades:sociedad' pk=sociedad.pk %}">{{ sociedad.nombre }}</a></td>
                        <td>{{ sociedad.fecha_creacion | date:'SHORT_DATE_FORMAT' }}</td>
                        <td>{{ sociedad.apoderado }}</td>
                        <td><span class="badge {{ sociedad.estado_badge }}">{{ sociedad.estado }}</span></td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">No se encontraron sociedades.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
    </div>
{% endblock content %}

sociedad/templates/sociedad/registrar.html
{% extends 'formset_registro_sociedad.html' %}
{% load static %}

{% block extra_js %}
    {% include 'includes/_select2.html' %}

    <script src="{% static 'js/jquery.formset.b4.js' %}"></script>

    <script>
        var socios = 0;
        $('.formulario-socio-inline').formset({
            prefix: "socios",
            addText: '<i class=" fa fa-plus fa-lg"></i> Nuevo Socio',
            added: function (row) {
                // console.log(row);
                row.find('.select').each(function() {
                    $(this).select2({theme: 'bootstrap4',});
                });
                row.find("[data-select2-id]").each(function() {
                    $(this).attr('style', 'width: 100% !important');
                });
                row.find('.numberinput').addClass('text-right').val(0);
            },
        });

        $('.formulario-inline').formset({
            prefix: "exporta",
            addText: '<i class=" fa fa-plus fa-lg"></i> Nuevo Lugar de Exportación',
            added: function (row) {
                row.find('.select').each(function() {
                    $(this).select2({theme: 'bootstrap4',});
                });
                row.find("[data-select2-id]").each(function() {
                    $(this).attr('style', 'width: 100% !important');
                });

                var pais = row.find("select[id*=pais]")

                datosPaises.forEach(country => {
                    const option = document.createElement('option')
                    option.value = country.code
                    option.innerText = country.name
                    pais.append(option)
                })

                var estado = row.find("select[id*=estado]")

                pais.on('select2:select', async e => {
                    const countryCode = e.target.value
                    const states = await getCountriesStates(countryCode)
                    estado.empty()
                    states.forEach(state => {
                        const option = document.createElement('option')
                        option.value = state.name
                        option.innerText = state.name
                        // console.log('asd')
                        estado.append(option)
                    })
                })
            }
        });

        $().ready(function () {
            $('.formulario-inline').find('.select').each(function() {
                $(this).select2({theme: 'bootstrap4',});
            });
            $('.formulario-inline').find("[data-select2-id]").each(function() {
                $(this).attr('style', 'width: 100% !important');
            });
            $('.formulario-dom-real-inline').find('.select').each(function() {
                $(this).select2({theme: 'bootstrap4',});
            });
            $('.formulario-dom-real-inline').find("[data-select2-id]").each(function() {
                $(this).attr('style', 'width: 100% !important');
            });
            $('.formulario-dom-legal-inline').find('.select').each(function() {
                $(this).select2({theme: 'bootstrap4',});
            });
            $('.formulario-dom-legal-inline').find("[data-select2-id]").each(function() {
                $(this).attr('style', 'width: 100% !important');
            });
            $('.formulario-socio-inline').find('.select').each(function() {
                $(this).select2({theme: 'bootstrap4',});
            });
            $('.formulario-socio-inline').find("[data-select2-id]").each(function() {
                $(this).attr('style', 'width: 100% !important');
            });
            
            $('.formulario-socio-inline').find('.numberinput').each(function(){
                if ($(this).val()!=0){
                    $(this).addClass('text-right');
                } else {
                    $(this).addClass('text-right').val(0);
                }
                
            })
            // $('.formulario-socio-inline').find('.numberinput').addClass('text-right').val(0);
        });

        const countrySelect = document.getElementById('id_exporta-0-pais')
        const stateSelect = document.getElementById('id_exporta-0-estado')

        const countrySelectDomReal = document.getElementById('id_dom_real-0-pais_dom_real')
        const stateSelectDomReal = document.getElementById('id_dom_real-0-estado_dom_real')

        const countrySelectDomLegal = document.getElementById('id_dom_legal-0-pais_dom_legal')
        const stateSelectDomLegal = document.getElementById('id_dom_legal-0-estado_dom_legal')

        var datosPaises = null

        queryFetch(`
            query{
                countries {
                    name
                    code
                }
            }
        `).then(data => {
            datosPaises = data.data.countries
            // var option = document.createElement('option')
            // option.innerText = '-------'
            // option.value = ''
            // countrySelect.append(option)
            $(".formulario-inline").each(function() {
                var prueba = document.getElementById($(this).children(":first").children(":first").children(":first").attr("id"));
                var option = document.createElement('option')
                option.innerText = '-------'
                option.value = ''
                prueba.append(option)
                data.data.countries.forEach(country => {
                    var option = document.createElement('option')
                    option.value = country.code
                    option.innerText = country.name
                    prueba.append(option)
                })
                $(this).on('select2:select', async e => {
                    var estado = $(this).children().eq(1).children(":first").children(":first")
                    const countryCode = e.target.value
                    const states = await getCountriesStates(countryCode)
                    estado.empty()
                    states.forEach(state => {
                        const option = document.createElement('option')
                        option.value = state.name
                        option.innerText = state.name
                        estado.append(option)
                    })
                })
            });
            data.data.countries.forEach(country => {
                // var option = document.createElement('option')
                // option.value = country.code
                // option.innerText = country.name
                // countrySelect.append(option)
                option = document.createElement('option')
                option.value = country.code
                option.innerText = country.name
                countrySelectDomReal.append(option)
                option = document.createElement('option')
                option.value = country.code
                option.innerText = country.name
                countrySelectDomLegal.append(option)
            })
        })

        $('#id_exporta-0-pais').on('select2:select', async e => {
            const countryCode = e.target.value
            const states = await getCountriesStates(countryCode)
            stateSelect.length = 0
            states.forEach(state => {
                const option = document.createElement('option')
                option.value = state.name
                option.innerText = state.name
                stateSelect.append(option)
            })
        })

        $('#id_dom_real-0-pais_dom_real').on('select2:select', async e => {
            const countryCode = e.target.value
            const states = await getCountriesStates(countryCode)
            stateSelectDomReal.length = 0
            states.forEach(state => {
                const option = document.createElement('option')
                option.value = state.name
                option.innerText = state.name
                stateSelectDomReal.append(option)
            })
        })

        $('#id_dom_legal-0-pais_dom_legal').on('select2:select', async e => {
            const countryCode = e.target.value
            const states = await getCountriesStates(countryCode)
            stateSelectDomLegal.length = 0
            states.forEach(state => {
                const option = document.createElement('option')
                option.value = state.name
                option.innerText = state.name
                stateSelectDomLegal.append(option)
            })
        })

        function getCountriesStates(countryCode) {
            return queryFetch(`
                query getStates($code: ID!) {
                    country(code: $code) {
                        states {
                            name
                            code
                        }
                    }
                }
            `, {code: countryCode }).then(data => {
                return data.data.country.states
            })
        }

        function queryFetch(query, variables) {
            return fetch('https://countries.trevorblades.com/', {
                method: 'POST',
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    query: query,
                    variables: variables
                })
            }).then(res => res.json())
        }

    </script>


{% endblock extra_js%}

sociedad/templates/sociedad/ver.html
{% extends 'base.html' %}

{% block title %}Sociedad{% endblock title %}

{% block content %}
    <div class="card border-info">
        <div class="card-body">
            <h2 class="card-title">Sociedad: {{ sociedad.nombre }}</h2>
            <div class="mb-3">
                <h3 class="text-right"><span id="estado" class="badge {{ sociedad.estado_badge }} badge-lg">{{ sociedad.estado }}</span></h3>
                <ul class="list-unstyled">
                    <li><strong>Fecha de Creación:</strong> {{ sociedad.fecha_creacion | date:'SHORT_DATE_FORMAT' }}</li>
                    <li><strong>Apoderado:</strong> {{ sociedad.apoderado | default_if_none:'-' }}</li>
                    <li><strong>Email:</strong> {{ sociedad.email }}</li>
                    <li><strong>Nro Expediente:</strong> {{ sociedad.nro_expediente | default_if_none:'-' }}</li>
                    <li><strong>Domicilio Real:</strong> {{ sociedad.domicilio_real }}</li>
                    <li><strong>Domicilio Legal:</strong> {{ sociedad.domicilio_legal }}</li>
                    <table>
                        <tr>
                            <td><strong>Archivo Estatuto</strong></td>
                            <td><a href="{{ sociedad.archivo_estatuto.url }}" download="{{ sociedad.archivo_estatuto.url }}"><i class="fas fa-file-download fa-2x"></i></a></td>
                        </tr>
                    </table>
                    {% if sociedad.url_drive %}
                        <li><a href="{{ sociedad.url_drive }}"><strong>URL Carpeta Digital</strong></a></li>
                    {% endif %}
                </ul>

                <ul class="list-unstyled">
                    <li><strong>Socios:</strong></li>
                    {% for socio in sociedad.socio.all %}
                    <li><strong>Nombre:</strong> {{ socio }} - <strong>Aporte:</strong> {{socio.aporte}}</li>
                    {% endfor %}
                </ul>

                <ul class="list-unstyled">
                    {% if sociedad.paises_exportados.all %}
                        <li><strong>Paises Exportados:</strong></li>
                        {% for pais in sociedad.paises_exportados.all %}
                        <li><strong>{{ pais }}</strong></li>
                        {% endfor %}
                    {% else %}
                        <li><strong>NO EXPORTA</strong></li>
                    {% endif %}
                </ul>
                {% if sociedad.imagen_qr %}
                    <img src="{{ sociedad.imagen_qr }}">
                {% endif %}

            </div>

            <div class="mt-3" id="botones">
                {% if sociedad.estado == "Pendiente" and not user.empleado_mesa_entrada and not user.empleado_area_legales %}
                    <a href="{% url 'sociedades:editar' pk=sociedad.pk %}" class="btn btn-info">Editar</a>
                    <a href="{% url 'sociedades:cerrar' pk=sociedad.pk %}" class="btn btn-success">Cerrar</a>
                {% endif %}
                {% if sociedad.estado == "Cerrada" and user.empleado_mesa_entrada %}
                    <a href="{% url 'sociedades:rechazar' pk=sociedad.pk %}" class="btn btn-danger">Rechazar</a>
                    <a href="{% url 'sociedades:revisar' pk=sociedad.pk %}" class="btn btn-success">Revisar</a>
                {% endif %}
                {% if sociedad.estado == "Revisada" and user.empleado_area_legales %}
                    <a href="{% url 'sociedades:rechazar_confirmacion' pk=sociedad.pk %}" class="btn btn-danger">Rechazar Confirmación</a>
                    <a href="{% url 'sociedades:confirmar' pk=sociedad.pk %}" class="btn btn-success">Confirmar</a>
                {% endif %}
                {% if sociedad.estado == "Confirmada" and user.empleado_mesa_entrada %}
                    <a href="{% url 'sociedades:carpetas_generadas' pk=sociedad.pk %}" class="btn btn-success">Carpetas Generadas</a>
                {% endif %}
                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#logModal">
                    Log
                </button>
                <a href="{{ url_cancelar }}" class="btn btn-primary">Volver</a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="logModal" tabindex="-1" role="dialog" aria-labelledby="logModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="logModalLabel">Log</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-striped table-sm">
                            <thead>
                            <tr>
                                <th scope="col">Fecha</th>
                                <th scope="col">Operador</th>
                                <th scope="col">Descripción</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for log in logs %}
                                <tr>
                                    <th scope="row">{{ log.fecha | date:"d/m/Y H:i" }}</th>
                                    <td>{{ log.usuario.username }}</td>
                                    <td>{{ log.descripcion }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}