rsa/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.urls import re_path as url
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("", include("users.urls", namespace="users")),
    # Your stuff: custom urls includes go here
    path('core/', include('core.urls', namespace='core')),
    path("sociedad/", include("sociedad.urls", namespace="sociedades")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [path('', include('login.urls', namespace='login')), ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

sociedad/urls.py
from django.urls import path

from .resources import ContinenteMasExportadoApi, LenguajeMasExportadoApi, EstadosMasRegistradoApi, ContinenteNoExportadoApi, RechazadosApi, \
    CantidadEsperaApi, CantidadAutoaceptadosApi, CantidadDiasProcesoApi, CantidadDiasMesaEntradaApi, CantidadDiasAreaLegalesApi
from .views import Registrar, Listar, SociedadVer, SociedadVer, Editar, Cerrar, Revisar, Rechazar, Confirmar, RechazarConfirmacion, SociedadVerPublico, \
    CarpetasGeneradas

app_name = 'liquidacion'

urlpatterns = [
    path('registrar', Registrar.as_view(), name='registrar'),
    path('listar-sociedades', Listar.as_view(), name='listar'),
    path('sociedad/<int:pk>', SociedadVer.as_view(), name='sociedad'),
    path('editar/<int:pk>', Editar.as_view(), name='editar'),
    path('cerrar/<int:pk>', Cerrar.as_view(), name='cerrar'),
    path('revisar/<int:pk>', Revisar.as_view(), name='revisar'),
    path('rechazar/<int:pk>', Rechazar.as_view(), name='rechazar'),
    path('confirmar/<int:pk>', Confirmar.as_view(), name='confirmar'),
    path('rechazar-confirmacion/<int:pk>', RechazarConfirmacion.as_view(), name='rechazar_confirmacion'),
    path('publica/<str:hash>', SociedadVerPublico.as_view(), name='sociedad_publica'),
    path('carpetas-generadas/<int:pk>', CarpetasGeneradas.as_view(), name='carpetas_generadas'),

    #API
    path('continentes-mas-exportados', ContinenteMasExportadoApi.as_view(), name='continentes_mas_exportados'),
    path('lenguaje-mas-exportados', LenguajeMasExportadoApi.as_view(), name='lenguaje_mas_exportados'),
    path('estados-mas-registrados', EstadosMasRegistradoApi.as_view(), name='estados_mas_registrados'),
    path('continentes-no-exportados', ContinenteNoExportadoApi.as_view(), name='continentes_no_exportados'),

    #API DATOS
    path('rechazados', RechazadosApi.as_view(), name='rechazados'),
    path('cantidad-espera', CantidadEsperaApi.as_view(), name='cantidad_espera'),
    path('cantidad-autoaceptados', CantidadAutoaceptadosApi.as_view(), name='cantidad_autoaceptados'),
    path('cantidad-dias-proceso', CantidadDiasProcesoApi.as_view(), name='cantidad_dias_proceso'),
    path('cantidad-dias-mesa-entrada', CantidadDiasMesaEntradaApi.as_view(), name='cantidad_dias_mesa_entrada'),
    path('cantidad-dias-area-legales', CantidadDiasAreaLegalesApi.as_view(), name='cantidad_dias_area_legales'),
]

users/urls.py
from django.urls import path

from .views import Logout, Escritorio

app_name = "users"

urlpatterns = [
    path('', Escritorio.as_view(), name='home'),
    path('logout/', Logout.as_view(), name='logout'),
]

templates/includes/_botones_formulario_ajax.html
<button type="button" class="btn btn-primary" id="boton_aceptar">Aceptar</button>
{% if url_cancelar %}
    <a href="{{ url_cancelar }}" class="btn btn-danger">Cancelar</a>
{% endif %}

templates/includes/_botones_formulario_standar.html
<input type="submit" name="submit" value="Aceptar" class="btn btn-primary" id="submit-id-submit">
{% if url_cancelar %}
    <a href="{{ url_cancelar }}" class="btn btn-danger">Cancelar</a>
{% endif %}

<script type="text/javascript">
    $(function () {
        var form_being_submitted = false;
        $("#formulario").submit(function (e) {
            if (form_being_submitted) {
                alert("Momento por favor, se estan procesando los datos...");
                e.preventDefault();
                return;
            }
            form_being_submitted = true;
        });
    });
</script>

templates/includes/_select2.html
<script>
    $(function(){
        $('.select').each(function() {
            $(this).select2({theme: 'bootstrap4', width: '100%', language: "es",});
        });
    });
</script>

templates/includes/css.html
{% load static %}
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

<!-- Latest compiled and minified Bootstrap CSS -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
  integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"> -->

<!-- bootstrap 4 -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

<!-- Font Awesome Free -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
      integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

<!-- Bootstrap Table CSS -->
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.css">


<!-- Your stuff: Third-party CSS libraries go here -->
<!-- Font Awesome Free -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css"
  integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

<!-- Timepicker -->
<link rel="stylesheet" href="{% static 'vendor/bootstrap-datepicker-1.6.4-dist/css/bootstrap-datepicker3.min.css' %}">


<!-- Select 2 -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="{% static 'css/select2-bootstrap4-theme.css' %}">


<!-- This file stores project-specific CSS -->
<link href="{% static 'css/project.css' %}" rel="stylesheet">

templates/includes/footer.html
<!-- Site footer -->
<footer>
  <div class="container">
      <div class="row">
          <div class="col-xs">
              Desarrollo de Software en Sistemas Distribuidos - Grupo 17
          </div>
          <div class="col"> </div>
          <div class="col-xs">
              <i class="fa fa-copyright"></i> {% now 'Y' %}
          </div>
      </div>
</footer>

templates/includes/js.html
{% load static %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/bootstrap-table.min.js"></script>

<!-- Latest compiled and minified Locales -->
<script src="https://unpkg.com/bootstrap-table@1.14.2/dist/locale/bootstrap-table-es-AR.js"></script>

<!-- Timepicker -->
<script src="{% static 'vendor/bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js' %}"
        type="application/javascript"></script>
<script src="{% static 'vendor/bootstrap-datepicker-1.6.4-dist/locales/bootstrap-datepicker.es.min.js' %}"
        type="application/javascript"></script>

<!-- Select 2 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/i18n/es.js"></script>

<!-- Your stuff: Third-party javascript libraries go here -->
{% if DEBUG %}
<script src="{% static 'js/project.js' %}"></script>
{% endif %}

<!-- place project specific Javascript in this file -->

templates/includes/messages.html
{% load static %}
<div class="container" id="mensajes">
{% if messages %}
{% for message in messages %}
  <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
{% endfor %}
{% endif %}
{% if form.errors %}
{% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ error|escape }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load static %}
{% load i18n %}
{% load flatpages %}
{% get_flatpages as flatpages %}


      <nav class="navbar navbar-expand-md shadow-lg color-rsa">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"><i class="fas fa-bars" style="color:#fff; font-size:28px;"></i></span>
        </button>
        <a class="navbar-brand" href="{% url 'users:home' %}">Registro de Sociedades Anónimas</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="dropdownApis" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">APIS<span class="caret"></span>
              </a>
              <div class="dropdown-menu" aria-labelledby="dropdownApis">
                <a class="dropdown-item" href="{% url 'sociedades:continentes_mas_exportados' %}">Continentes Más Exportados</a>
                <a class="dropdown-item" href="{% url 'sociedades:lenguaje_mas_exportados' %}">Lenguajes Más Exportados</a>
                <a class="dropdown-item" href="{% url 'sociedades:estados_mas_registrados' %}">Estados Más Registrados</a>
                <a class="dropdown-item" href="{% url 'sociedades:continentes_no_exportados' %}">Continentes No Exportados</a>
              </div>
            </li>
          </ul>

          {% if request.user.is_authenticated %}
            {% if not request.user.personal_direccion %}
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'sociedades:listar' %}">Sociedades Anónimas</a>
                </li>
              </ul>
            {% endif %}
        </div>
            
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="dropdownUser" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">{{ request.user.username }}<span class="caret"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownUser">
                {% if request.user.is_staff %}
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}
                <a class="dropdown-item" href="{% url 'users:logout' %}">Salir</a>
              </div>
            </li>
          </ul>
          {% endif %}
        </div>
      </nav>